#!/bin/bash

################################################################################
# This script allows you to easily handle development docker images
################################################################################

# styleguide: https://google.github.io/styleguide/shellguide.html

# saner programming env: these switches turn some bugs into errors
#
set -o pipefail -o noclobber -o nounset

################################################################################
# Globals
################################################################################

uid=$(id -u)
gid=$(id -g)
default_image_name="dev"
default_container_name="dev"
default_docker_file_name="Dockerfile"

################################################################################
# Utils
################################################################################

function __script_directory_path() {
    local script_link
    script_link=$(readlink -f "$0")
    local script_dir
    script_dir=$(dirname "${script_link}")
    echo "${script_dir}"
}

function __script_directory_name() {
    echo "$(basename $(__script_directory_path))"
}

################################################################################
# Docker functions
################################################################################

function __docker_build() {
    local image_name="$1"
    local docker_file="$2"
    local docker_dir=$(dirname "${docker_file}")
    docker build \
        --build-arg uid="${uid}" \
        --build-arg gid="${gid}" \
        --build-arg home="${HOME}" \
        --no-cache \
        -t "${image_name}" \
        -f "${docker_file}" \
        "${docker_dir}"
}

function __docker_up() {
    local image_name="$1"
    local container_name="$2"
    local docker_extra_args="$3"
    local container_id
    container_id=$(docker ps --all --filter "name=^/${container_name}$" --format "{{.ID}}")
    if [[ -z "${container_id}" ]]; then
        __docker_create "${image_name}" "${container_name}" "${docker_extra_args}"
    fi

    __docker_start "${container_name}"
    __docker_attach "${container_name}"
}

function __docker_stop() {
    local container_name="$1"
    docker stop "${container_name}" 1>/dev/null
}

function __docker_destroy() {
    local container_name="$1"
    __docker_stop "${container_name}"
    __docker_remove_container "${container_name}"
}

function __default_docker_args() {
    local container_name="$1"
    local args=''
    args+="--interactive "
    args+="--tty "
    args+="--user ${uid}:${gid} "
    args+="--name ${container_name} "
    args+="--volume /etc/group:/etc/group:ro "
    args+="--volume /etc/passwd:/etc/passwd:ro "
    args+="--volume /etc/shadow:/etc/shadow:ro "
    args+="--volume /etc/sudoers.d:/etc/sudoers.d:ro "
    args+="--volume ${HOME}/dev:${HOME}/dev "
    args+="--volume ${HOME}/.bashrc:${HOME}/.bashrc "
    args+="--volume ${HOME}/.bash_profile:${HOME}/.bash_profile "
    args+="--volume ${HOME}/.gitconfig:${HOME}/.gitconfig "
    args+="--volume ${HOME}/.tmux.conf:${HOME}/.tmux.conf "
    args+="--volume ${HOME}/.vim:${HOME}/.vim "
    args+="--volume ${HOME}/.vimrc:${HOME}/.vimrc "
    args+="--volume ${HOME}/.ssh:${HOME}/.ssh "
    args+="--volume ${HOME}/.jupyter:${HOME}/.jupyter "
    args+="--volume ${HOME}/.docker_bash_history:${HOME}/.bash_history "
    echo "${args}"
}

function __docker_create() {
    local image_name="$1"
    local container_name="$2"
    local docker_extra_args="$3"
    local docker_default_args
    docker_default_args=$(__default_docker_args "${container_name}")
    local docker_all_args="${docker_default_args} ${docker_extra_args}"

    # we need this array to stop shellcheck complaining about docker create call
    local docker_args=()
    for arg in ${docker_all_args}; do
        docker_args+=("${arg}")
    done

    docker create "${docker_args[@]}" "${image_name}" 1>/dev/null
}

function __docker_start() {
    local container_name="$1"
    docker start "${container_name}" 1>/dev/null
}

function __docker_attach() {
    local container_name="$1"
    docker exec -it "${container_name}" bash
}

function __docker_list_containers() {
    docker ps -a
}

function __docker_list_images() {
    docker image ls
}

function __docker_remove_container() {
    local container_name="$1"
    docker rm "${container_name}" 1>/dev/null
}

function __docker_remove_image() {
    local image_name="$1"
    docker rmi "${image_name}" 1>/dev/null
}


################################################################################
# Script
################################################################################

function __script_help() {
    echo "Docker wrapper for development docker image"
    echo "Options:"
    echo "  -h, --help             Options description"
    echo "  -b, --build            Build image"
    echo "  -c, --create           Create container"
    echo "  -s, --start            Start an existing container"
    echo "  -a, --attach           Attach to a running container"
    echo "  -S, --stop             Stop a running container"
    echo "  -r, --remove_container Remove an existing container"
    echo "  -R, --remove_image     Remove an existing image"
    echo "  -u, --up               Start a container (create if not exists) and attach to it"
    echo "  -l, --list_containers  List info on all containers"
    echo "  -L, --list_images      List info on all images"
    echo "  -d, --destroy          Stop container and delete it"
    echo "  -F, --docker_file      Path to the docker file, default is <SCRIPTS_CURRENT_DIR>/${default_docker_file_name}"
    echo "  -I, --image_name       Name of the image"
    echo "  -C, --container_name   Name of the container"
    echo "Additional parameters are listed after -- and passed to docker"
    echo "Examples:"
    echo "  ./d -b                                # Build container"
    echo "  ./d -b --docker_file ~/myDockerfile   # Build container"
    echo "  ./d -u                                # Run and attach to container"
    echo "  ./d -s -                              # Stop container and delete it"
    echo "  ./d -b -u --publish 8080              # Build container, run it with open port 8080 and attach"
}

function __main() {
    local args=("$@")
    local args_length=${#args[@]}

    local docker_extra_args=""
    local docker_extra_args_started=0

    local image_name=""
    local container_name=""
    local docker_file=""

    local commands=()
    for ((i=0; i<args_length; )); do
        local arg=${args[${i}]}
        case "${arg}" in
            -h|--help)
                commands+=("help")
                ;;
            -b|--build)
                commands+=("build")
                ;;
            -c|--create)
                commands+=("create")
                ;;
            -d|--destroy)
                commands+=("destroy")
                ;;
            -s|--start)
                commands+=("start")
                ;;
            -a|--attach)
                commands+=("attach")
                ;;
            -S|--stop)
                commands+=("stop")
                ;;
            -r|--remove_container)
                commands+=("remove_container")
                ;;
            -R|--remove_image)
                commands+=("remove_image")
                ;;
            -u|--up)
               commands+=("up")
                ;;
            -l|--list_containers)
                commands+=("list_containers")
                ;;
            -L|--list_images)
                commands+=("list_images")
                ;;
            -F|--docker_file)
                ((i+=1))
                docker_file=${args[${i}]}
                ;;
            -I|--image_name)
                ((i+=1))
                image_name=${args[${i}]}
                ;;
            -C|--container_name)
                ((i+=1))
                container_name=${args[${i}]}
                ;;
            --)
                docker_extra_args_started=1
                ;;
            *)
                if (( docker_extra_args_started == 0)); then
                    echo "Can\'t parse arguments. Unknown argument ${arg}"
                    __script_help
                    exit 1
                fi
                docker_extra_args+="${arg} "
                ;;
        esac
        ((i+=1))
    done

    for command in "${commands[@]}"; do
        if [[ ${command} == "help" ]]; then
            __script_help
        fi
        if [[ ${command} == "build" ]]; then
            if [[ -z "${image_name}" ]]; then
                image_name="${default_image_name}"
            fi
            if [[ -z "${docker_file}" ]]; then
                docker_file="$(__script_directory_path)/${default_docker_file_name}"
            fi
            __docker_build "${image_name}" "${docker_file}"
        fi
        if [[ ${command} == "create" ]]; then
            if [[ -z "${image_name}" ]]; then
                image_name="${default_image_name}"
            fi
            if [[ -z "${container_name}" ]]; then
                container_name="${default_container_name}"
            fi
            __docker_create "${image_name}" "${container_name}" "${docker_extra_args}"
        fi
        if [[ ${command} == "destroy" ]]; then
            if [[ -z "${container_name}" ]]; then
                container_name="${default_container_name}"
            fi
            __docker_destroy "${container_name}"
        fi
        if [[ ${command} == "start" ]]; then
            if [[ -z "${container_name}" ]]; then
                container_name="${default_container_name}"
            fi
            __docker_start "${container_name}"
        fi
        if [[ ${command} == "attach" ]]; then
            if [[ -z "${container_name}" ]]; then
                container_name="${default_container_name}"
            fi
            __docker_attach "${container_name}"
        fi
        if [[ ${command} == "stop" ]]; then
            if [[ -z "${container_name}" ]]; then
                container_name="${default_container_name}"
            fi
            __docker_stop "${container_name}"
        fi
        if [[ ${command} == "remove_container" ]]; then
            if [[ -z "${container_name}" ]]; then
                container_name="${default_container_name}"
            fi
            __docker_remove_container "${container_name}"
        fi
        if [[ ${command} == "remove_image" ]]; then
            if [[ -z "${container_name}" ]]; then
                container_name="${default_container_name}"
            fi
            __docker_remove_image "${container_name}"
        fi
        if [[ ${command} == "up" ]]; then
            if [[ -z "${image_name}" ]]; then
                image_name="${default_image_name}"
            fi
            if [[ -z "${container_name}" ]]; then
                container_name="${default_container_name}"
            fi
            __docker_up "${image_name}" "${container_name}" "${docker_extra_args}"
        fi
        if [[ ${command} == "list_containers" ]]; then
            __docker_list_containers
        fi
        if [[ ${command} == "list_images" ]]; then
            __docker_list_images
        fi
    done
}

__main "$@"
